# The MIT License (MIT)
#
# Copyright (c) 2015 Keith Davidson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

- name: checkout w3c-unicorn source
  hg:
    repo: "https://dvcs.w3.org/hg/unicorn"
    dest: "/home/{{install_user}}/unicorn"
    force: yes
    purge: yes
  tags:
    - w3cunicorn

- name: build unicorn.war
  command: ant retrieve default_conf war
  args:
    chdir: "/home/{{install_user}}/unicorn"
  tags:
    - w3cunicorn

- name: remove old unicorn.war if exists
  file:
    path: /var/lib/tomcat7/webapps/unicorn.war
    state: absent
  tags:
    - w3cunicorn

- name: remove old unicorn.war if exists
  file:
    path: /var/lib/tomcat7/webapps/unicorn
    state: absent
  tags:
    - w3cunicorn

- name: deploy unicorn.war to tomcat
  command: "cp /home/{{install_user}}/unicorn/dist/unicorn.war /var/lib/tomcat7/webapps"
  notify:
    - restart tomcat7
  tags:
    - w3cunicorn

- name: remove old unicorn.war if exists
  file:
    path: /var/lib/tomcat7/tomcat-users.xml
    state: absent
  tags:
    - w3cunicorn

- name: deploy tomcat users file
  template:
    src: tomcat-users.xml.j2
    dest: "/etc/tomcat7/tomcat-users.xml"
  notify:
    - restart tomcat7
  tags:
    - w3cunicorn
